sugarcube-2:
  macros:

    # live-update.js
    live:
      name: live
    l:
      name: l
    lh:
      name: lh
    liveblock:
      name: liveblock
      container: true
    lb:
      name: lb
      container: true
    update:
      name: update
    upd:
      name: upd

    # click-to-proceed.js
    ctp:
      name: ctp
      container: true
      children:
        - ctpNext
        - ctpHead
        - ctpTail
      description: |-
        The main CTP macro inside which all content is written.

        Usage:
        ```
        <<ctp id [keywords]>>
          …
        <</ctp>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctp-id-keywords)
    ctpNext:
      name: ctpNext
      parents:
        - ctp
      description: |-
        To be used inside `<<ctp>>` to separate the content into blocks.
        
        Usage:
        ```
        <<ctpNext [keywords]>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctpnext-keywords)
    ctpHead:
      name: ctpHead
      parents:
        - ctp
      description: |-
        To be used inside `<<ctp>>` as a block *prepended* to the chain which is re-evaluated at every `<<ctpAdvance>>` and `<<ctpBack>>`. As long as it is inside `<<ctp>>`, the position does not matter.
        
        Usage:
        ```
        <<ctpHead [keywords]>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctphead-keywords)
    ctpTail:
      name: ctpTail
      parents:
        - ctp
      description: |-
        To be used inside `<<ctp>>` as a block *appended* to the chain which is re-evaluated at every `<<ctpAdvance>>` and `<<ctpBack>>`. As long as it is inside `<<ctp>>`, the position does not matter.
        
        Usage:
        ```
        <<ctpTail [keywords]>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctptail-keywords)
    ctpAdvance:
      name: ctpAdvance
      description: |-
        The 'proceed' part of Click To Proceed... Used to move the train forward and show the next blocks.
        
        Usage:
        ```
        <<ctpAdvance id>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctpadvance-id)
    ctpBack:
      name: ctpBack
      description: |-
        Turns back time and goes back one block.
        
        Usage:
        ```
        <<ctpBack id>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/click-to-proceed#ctpback-id)
    
    # crossfade.js
    crossfadecontainer:
      name: crossfadecontainer
      description: |-
        Creates a container to use for crossfading between images.

        Usage:
        ```
        <<crossfadecontainer id [initialImagePath]>>
        ```
      parameters:
        - text |+ text
    crossfade:
      name: crossfade
      description: |-
        Crossfades between new image and image already in a pre-defined `<<crossfadecontainer>>`.
        
        Usage:
        ```
        <<crossfade id imagePath [fadeDuration]>>
        ```
      parameters:
        - text &+ text |+ text
    
    # narrative-tree.js
    treebranch:
      name: treebranch
      container: true
      children:
        - leaf
      description: |-
        Defines a branch on a registered NTree.

        Usage:
        ```
        <<treebranch NTreeID NTreeBranchID [norepeat|repeatlast|repeat]>>
          …
        <</treebranch>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/narrative-tree#a-macro-treebranch)
      parameters:
        - string &+ string |+ "norepeat"|"repeatlast"|"repeat"
    leaf:
      name: leaf
      parents:
        - treebranch
      description: |-
        Defines a leaf on an NTree branch.

        Usage:
        ```
        <<leaf [provider update object]>>
          …
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/narrative-tree#a-macro-leaf)
      skipArgs: true