sugarcube-2:
  macros:
    treebranch:
      name: treebranch
      container: true
      children:
        - leaf
      description: |-
        Defines a branch on a registered NTree.

        Usage:
        ```
        <<treebranch NTreeID NTreeBranchID [norepeat|repeatlast|repeat]>>
          …
        <</treebranch>>
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/narrative-tree#a-macro-treebranch)
      parameters:
        - string &+ string |+ "norepeat"|"repeatlast"|"repeat"
    leaf:
      name: leaf
      parents:
        - treebranch
      description: |-
        Defines a leaf on an NTree branch.

        Usage:
        ```
        <<leaf [provider update object]>>
          …
        ```
        READ: [Documentation](https://github.com/cyrusfirheir/cycy-wrote-custom-macros/tree/master/narrative-tree#a-macro-leaf)
      skipArgs: true